### ISSUE TITLE
Avoid as.formula()

### ISSUE THREAD

**Issue by cpsievert** [zappingseb/shinymetaTest#1]
The following is a security vulnerability (if you're curious why, run `lm(as.formula("1 ~ system('ls')"))`):

```r
as.formula(paste("AVAL", paste(input$select_regressor, collapse = " + "), sep = " ~ "))
```

It'd be safer to do something like this:

```r
library(rlang)
preds <- Reduce(function(x, y) call("+", x, y), syms(input$select_regressor))
new_formula(sym("AVAL"), preds)
```

**Comment by cpsievert** [comment]
Ahh, or do something like this: https://github.com/zappingseb/shinymetaTest/commit/fa7f5787e618975009985c984b768f6f5f4bd16f

**Comment by cpsievert** [comment]
FWIW the README and this post still show the un-secure way 

https://towardsdatascience.com/shinymeta-a-revolution-for-reproducibility-bfda6b329f68

**Comment by zappingseb** [comment]
Thanks a lot @cpsievert. I was not aware of this

Updated gists for Medium entry:

- https://gist.github.com/zappingseb/4ade142cf762e1f47d42661790b2e13c/revisions
- https://gist.github.com/zappingseb/2e03d7531971386f5fd340ab3401854b/revisions

Updated Code in Commit [45465c0](https://github.com/zappingseb/shinymetaTest/commit/45465c0ad1609d20127e70dad1ed437c5ac34d09)

Is it ok for you?
